Add Russian Language ru_RU Support for Space Acres
autonomys/space-acres pull request #291
Opened 2024-08-20 12:53 UTC by Inoutik

This commit adds the Russian Language in Space Acres interface

2024-08-22 07:40 UTC, EmilFattakhov requested changes
Спасибо большое за перевод!

Оставил несколько предложений чтобы сделать некоторые из фраз более понятными.

2024-08-22 08:11 UTC, Inoutik commented on res/translations/ru-RU/messages.ftl
> +error_message_failed_to_send_pause_plotting_to_backend = Не удалось приостановить плоттинг на движке: {$error}
Долго думал как тут лучше сформулировать, мб еще что то типо такого, без указания что есть какой то бэкенд - Не удалось приостановить плоттинг: {$error}

2024-08-22 10:38 UTC, EmilFattakhov commented on res/translations/ru-RU/messages.ftl
> +error_message_failed_to_send_pause_plotting_to_backend = Не удалось приостановить плоттинг на движке: {$error}
@Inoutik согласен, мне так тоже больше нравится

2024-08-23 16:30 UTC, EmilFattakhov commented
@Inoutik lmk если нужна помощь чтобы сделать финальные изменения

2024-08-27 13:29 UTC, EmilFattakhov approved these changes
Спасибо @Inoutik!

2024-08-27 13:29 UTC, EmilFattakhov commented on res/translations/ru-RU/messages.ftl
> +    ✔ Любой твердотельный накопитель SSD (или несколько) с максимально возможным объемом памяти для фарминга. Чем больше объем - тем больше прибыль"
```suggestion
    ✔ Любой твердотельный накопитель SSD (или несколько) с максимально возможным объемом памяти для фарминга. Чем больше объем - тем больше прибыль
```

2024-08-27 13:29 UTC, EmilFattakhov commented on res/translations/ru-RU/messages.ftl
> +error_message_failed_to_send_pause_plotting_to_backend = Не удалось приостановить плоттинг на бэкенде: {$error}
```suggestion
error_message_failed_to_send_pause_plotting_to_backend = Не удалось приостановить плоттинг: {$error}
```

2024-08-27 13:30 UTC, EmilFattakhov commented
@nazar-pc this PR is good to merge!

2024-08-28 15:26 UTC, EmilFattakhov commented on res/translations/ru-RU/messages.ftl
> +configuration_farm = Путь к фарму {$index} и его размер
```suggestion
configuration_farm = Путь к ферме {$index} и её размер
```

2024-08-28 15:26 UTC, EmilFattakhov commented on res/translations/ru-RU/messages.ftl
> +configuration_farm_path_tooltip = Абсолютный путь к папке, в которой будут храниться данные фарма. Подойдет любой SSD-накопитель, высокая производительность не требуется
```suggestion
configuration_farm_path_tooltip = Абсолютный путь к папке, в которой будут храниться данные фермы. Подойдет любой SSD-накопитель, высокая производительность не требуется
```

2024-08-28 15:26 UTC, EmilFattakhov commented on res/translations/ru-RU/messages.ftl
> +configuration_farm_fixed_size_tooltip = Размер фарма в зависимости от того, какие единицы измерения вы предпочитаете. Подойдет любой размер свыше 2Гб
```suggestion
configuration_farm_fixed_size_tooltip = Размер фермы в зависимости от того, какие единицы измерения вы предпочитаете. Подойдет любой размер свыше 2Гб
```

2024-08-28 15:26 UTC, EmilFattakhov commented on res/translations/ru-RU/messages.ftl
> +configuration_farm_delete = Удалить этот фарм
```suggestion
configuration_farm_delete = Удалить эту ферму
```

2024-08-28 15:26 UTC, EmilFattakhov commented on res/translations/ru-RU/messages.ftl
> +configuration_farm_free_percentage_size_tooltip = Процент свободного места на диске, занимаемого фармом. Будет работать от 0%, но на диске должно оставаться не менее 2Гб свободного места для исключен
```suggestion
configuration_farm_free_percentage_size_tooltip = Процент свободного места на диске, занимаемого фермой. Будет работать от 0%, но на диске должно оставаться не менее 2Гб свободного места для исключения ошибок.
```

2024-08-28 15:26 UTC, EmilFattakhov commented on res/translations/ru-RU/messages.ftl
> +configuration_advanced_farmer_reduce_plotting_cpu_load = Уменьшить нагрузку на процессор при плоттинге фармов
```suggestion
configuration_advanced_farmer_reduce_plotting_cpu_load = Уменьшить нагрузку на процессор при плоттинге
```

2024-08-28 15:26 UTC, EmilFattakhov commented on res/translations/ru-RU/messages.ftl
> +configuration_button_add_farm = Добавить фарм
```suggestion
configuration_button_add_farm = Добавить ферму
```

2024-08-28 15:26 UTC, EmilFattakhov commented on res/translations/ru-RU/messages.ftl
> +running_farmer_button_expand_details = Показать детали о каждом фарме
```suggestion
running_farmer_button_expand_details = Показать детали о каждой ферме
```

2024-08-28 16:32 UTC, nazar-pc commented
@Inoutik you can submit multiple suggestions in a batch. Sending them individually generates ridiculous number of email notifications.

2024-08-28 19:28 UTC, EmilFattakhov commented on res/translations/ru-RU/messages.ftl
> +notification_farm_error = Один из фармов сломался в Space Acres
```suggestion
notification_farm_error = Одна из ферм сломалась в Space Acres
```

2024-08-28 19:30 UTC, EmilFattakhov commented
@Inoutik thanks again for picking this up and addressing the comments on the PR. @nazar-pc, please kindly have another look when you get a chance, should be all right!

2024-08-29 00:19 UTC, nazar-pc commented on res/translations/ru-RU/messages.ftl
> +    ✔ Любой твердотельный накопитель SSD (или несколько) с максимально возможным объемом памяти для фарминга. Чем больше объем - тем больше прибыль"
```suggestion
    ✔ Адрес кошелька, на который вы будете получать вознаграждения (используйте Subwallet, расширение polkadot{"{"}.js{"}"} или любой другой кошелек, совместимый с Substrate)
    ✔ 100Гб свободного места на твердотельном накопителе SSD хорошего качества для хранения данных блокчейна
    ✔ Любой твердотельный накопитель SSD (или несколько) с максимально возможным объемом памяти для фарминга. Чем больше объем - тем выше награда.
```

2024-08-29 00:19 UTC, nazar-pc commented on res/translations/ru-RU/messages.ftl
> +upgrade_button_upgrade = Обновление на {$chain_name}
```suggestion
upgrade_button_upgrade = Обновить до {$chain_name}
```

2024-08-29 00:19 UTC, nazar-pc commented on res/translations/ru-RU/messages.ftl
> +loading_configuration_step_configuration_not_found = Чтение конфигурации...
```suggestion
loading_configuration_step_configuration_exists = Конфигурация найдена...
loading_configuration_step_configuration_not_found = Конфигурация отсутствует..
```

2024-08-29 00:19 UTC, nazar-pc commented on res/translations/ru-RU/messages.ftl
> +loading_configuration_step_decoded_chain_spec = Спецификация блокчейна успешно расшифрована
```suggestion
loading_configuration_step_decoding_chain_spec = Обработка спецификации блокчейна...
loading_configuration_step_decoded_chain_spec = Спецификация блокчейна готова
```

2024-08-29 00:19 UTC, nazar-pc commented on res/translations/ru-RU/messages.ftl
> +loading_consensus_node_step_created_successfully = Узел блокчейна на основе консенсуса успешно создан
```suggestion
loading_consensus_node_title = Инициализация узла консенсуса
loading_consensus_node_step_creating = Создание узла консенсуса...
loading_consensus_node_step_created_successfully = Узел консенсуса успешно создана
```

2024-08-29 00:20 UTC, nazar-pc approved these changes

2024-08-29 00:46 UTC, merged